let cezalar = [
    {isim : "Disobeying Traffic Light Rules (1)", para : 500, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Exceeding The Speed Limit By 5+ (1)", para : 500, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Exceeding The Speed Limit By 10+", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Exceeding The Speed Limit By 20+", para : 1500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Exceeding The Speed Limit By 30+", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Driving An Illegal Vehicle On The Road (4)", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "Operating A Vehicle Without A License (10)", para : 3000, hapis :0, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Illegal Parking (1)", para : 500, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Hit And Run (4)", para : 5000, hapis :0, kamu :10, illegal : false, active : false, tceza : 4 },
    {isim : "Illegally Modified Vehicle (4)", para : 1500, hapis :0, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "Reckless Driving (1)", para : 5000, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Illegal Street Racing", para : 2500, hapis :0, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Bribery Of A Government Official", para : 1500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Insulting A Government Official", para : 500, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Threatening A LEO", para : 2500, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Fradulent Representation", para : 2500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Prostitution", para : 5000, hapis :0, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Cybercrime", para : 3000, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Grand Theft Auto Of A Government Vehicle(5)", para : 7500, hapis :50, kamu :0, illegal : false, active : false, tceza : 5 },
    {isim : "Grand Theft Auto(3)", para : 7000, hapis :0, kamu :0, illegal : false, active : false, tceza : 3 },
    {isim : "Disorderly Conduct", para : 3500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Assault", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Assault On A Government Official", para : 8000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Resisting Arrest", para : 5000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Fraudulent Activities", para : 4500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Failure To Heed A Stop Warning(4)", para : 3000, hapis :0, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "Perjury", para : 7500, hapis :0, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Associated With An Illegal Organization(10)", para : 10000, hapis :500, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Involuntary Manslaughter", para : 15000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Kidnapping", para : 10000, hapis :10, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Kidnapping Of A Government Official", para : 15000, hapis :30, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Illegal Betting", para : 3000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Act Of Terrorism(10)", para : 100000, hapis :1000, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Encouraging Or Assisting Someone To Commit A Crime", para : 3000, hapis :60, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Brandishing A Firearm", para : 3500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Obtaining A Molotov", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Fake Plate(2)", para : 2500, hapis :0, kamu :0, illegal : false, active : false, tceza : 2 },
    {isim : "Gang Related Shooting", para : 5000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Hostage Taking", para : 10000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Attempted Murder", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Second Degree Murder", para : 10000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "First Degree Murder", para : 15000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Attempted Murder Of A Government Official", para : 10000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Second Degree Murder Of A Government Official", para : 12500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "First Degree Murder Of A Government Official", para : 17500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Attempted Armed Robbery", para : 15000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Armed Robbery", para : 20000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Accessory To Armed Robbery", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Attempted Robbery", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Robbery", para : 12500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Accessory To Robbery", para : 5000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Impersonating A Government Official", para : 3500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Accessory To Jailbreak", para : 5500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Attempted Jailbreak", para : 6000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Jailbreak", para : 10000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Vandalism", para : 4500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Vandalism Of Government Property", para : 6000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Trespassing", para : 6500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Felony Trespassing", para : 9000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Arson", para : 12500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Harassment", para : 2500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "False Reporting", para : 2750, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Posession Of Stolen Identification", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Stalking", para : 1500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Evading", para : 7000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Reckless Evading", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Driving Under Influence", para : 8000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Driving Without Headlights Or Signals", para : 1750, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Illegal U-Turn", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Illegal Passing", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Failure To Stop", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Failure To Yield To An Emergency Vehicle", para : 4000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Negligent Driving", para : 3500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Animal Cruelty", para : 3000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Vehicular Manslaughter", para : 10000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Money Laundering", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Grand Larceny", para : 9000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Extortion", para : 10000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Burglary", para : 8500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Torture", para : 15000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Criminal Threats", para : 2500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Leaving Without Paying", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Tampering", para : 3500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Failure To Provide Identification", para : 1500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Unlawful Assembly", para : 2500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Inciting A Riot", para : 4500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Posession Of Non-Controlled Substance", para : 5500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Posession Of Narcotic", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Possession of Psychedelics", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Possession Over Legal Amount Of Controlled Substance", para : 7500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Jaywalking", para : 750, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
]
